updated animation of burb
cia-ulaval/EEG_flappy_bird pull request #10
Opened 2024-10-16 22:50 UTC by QuentinClyy

2024-10-16 23:32 UTC, VillyGH requested changes

2024-10-16 23:32 UTC, VillyGH commented on src/Bird.py
> +        if pygame.time.get_ticks() > self.jump_timer + 50:
À mettre en constante

2024-10-16 23:32 UTC, VillyGH commented on src/Bird.py
> +        self.jump_timer = pygame.time.get_ticks() + 95
À mettre en constante

2024-10-19 14:29 UTC, VillyGH approved these changes

2024-10-29 02:45 UTC, Louis-Etienne approved these changes
Good stuff Quentin!!

2024-10-29 02:45 UTC, merged