Cleanup + Reste stable avant le premier saut
cia-ulaval/EEG_flappy_bird pull request #12
Opened 2024-11-01 18:06 UTC by VillyGH

2024-11-02 03:31 UTC, QuentinClyy commented on src/GameConfig.py
pourquoi lajout de lignes ?

2024-11-02 03:33 UTC, QuentinClyy commented on src/GameManager.py
> +
ligne de trop

2024-11-02 03:36 UTC, QuentinClyy commented on src/Scoreboard.py
ligne de trop

2024-11-02 03:36 UTC, QuentinClyy commented on src/Scoreboard.py
ligne de trop

2024-11-02 03:37 UTC, QuentinClyy commented on src/Scoreboard.py
ligne de trop

2024-11-02 03:37 UTC, QuentinClyy commented on src/Scoreboard.py
ligne de trop

2024-11-02 03:38 UTC, QuentinClyy commented on src/util.py
> +# Utility python module whose objective is to bring
which's a la place de whose

2024-11-02 03:39 UTC, QuentinClyy requested changes
faire les ptits changements d'anglais et supprimer quelques lignes de trop pour une meilleure uniformite du code (peut etre remplacer services par functionalities ou enlever services)

2024-11-02 04:07 UTC, NicoTDev commented
Salut! Les sauts à la ligne que j'ai fait sont pour ne pas avoir d'erreur de PEP8, car une ligne ne doit pas dépasser les 120 caractères. En général, le fait de faire un saut entre des paramètres trop longs pour ne faire de lignes trop longues est correct. Pourquoi veut tu que je les mettes sur une ligne?

2024-11-02 04:34 UTC, VillyGH commented
Oui sinon l'ide montre une erreur

2024-11-02 04:52 UTC, QuentinClyy commented
> Salut! Les sauts à la ligne que j'ai fait sont pour ne pas avoir d'erreur de PEP8, car une ligne ne doit pas dépasser les 120 caractères. En général, le fait de faire un saut entre des paramètres trop longs pour ne faire de lignes trop longues est correct. Pourquoi veut tu les mettre sur une ligne?

Parfait, c'est juste github qui faisait un affichage différent alors !

2024-11-02 04:53 UTC, QuentinClyy commented
> Oui sinon Pycharm affiche un avertissement Sinon merci pour ta revue je vais faire les ajustements nécessaires :)

Parfait, tu me repokeras pour le review !

2024-11-02 20:35 UTC, VillyGH commented
J'ai fait quelques changements basé sur tes suggestions @QuentinClyy

2024-11-02 21:35 UTC, QuentinClyy commented
Which's ahahaha mais oh well, jtapprove ça

2024-11-02 21:36 UTC, QuentinClyy approved these changes

2024-11-02 23:01 UTC, VillyGH commented
Oh well flemme xD

2024-11-04 03:20 UTC, Louis-Etienne approved these changes
good stuff! j'aime la standardisation

2024-11-04 16:19 UTC, merged