+ajout du scoreboard +ajout gestion scene
cia-ulaval/EEG_flappy_bird pull request #7
Opened 2024-10-11 21:21 UTC by NicoTDev

+Ajout de la classe scoreboard
+Ajout de la gestion des scènes qui prend un enum pour savoir quoi afficher
+Ajouter de la gravité de l'oiseau et de sa rotation (peut-être à revoir)
=Séparation de quelques fonctions de GameConfig pour les utiliser séparément

2024-10-15 03:04 UTC, VillyGH commented on data/scores.json
à voir si possible de remplacer par du binaire

2024-10-15 03:07 UTC, VillyGH requested changes

2024-10-15 03:07 UTC, VillyGH commented on src/Scoreboard.py
> +                    font_color=[(183, 183, 3 ), (111, 111, 111), (147, 105, 50),(0, 0, 0)][min(index, 3)],
Constantes de couleur / font

2024-10-15 03:07 UTC, VillyGH commented on src/Scoreboard.py
> +            self.menu.add.label(title=f"{index+1:<{indentIndex}}"
Refactor / clareté du code

2024-10-15 03:10 UTC, VillyGH commented
S'assurer de ne pas être en conflit avec l'autre PR

2024-10-16 21:55 UTC, Louis-Etienne commented on src/Scoreboard.py
> +                    font_color=[(183, 183, 3 ), (111, 111, 111), (147, 105, 50),(0, 0, 0)][min(index, 3)],
On vient de mettre des constantes!

2024-10-16 21:56 UTC, Louis-Etienne commented on src/Scoreboard.py
> +            self.menu.add.label(title=f"{index+1:<{indentIndex}}"
le code est laid ahaha, mais compact, on a ajouté des commentaires pour le rendre plus compréhensif

2024-10-16 22:01 UTC, merged